hotel/urls.py
from django.urls import path
from hotel import views

urlpatterns = [
    path(r'', views.hotel, name="hotel"),
    path(r'detail/<int:hotel_id>/', views.hotel_detail, name="hotel_detail"),
    path(r'booking/<int:hotel_id>/', views.booking, name="booking"),
    path(r'booking_success/', views.success_booking, name="booking_success"),
    path(r'booking/detail/<int:booking_id>', views.booking_detail, name="booking_detail"),
    path("favorite/add/<int:hotel_id>", views.favorite, name='favorite'),
    path("favorite/", views.wishlist, name='user_favorite'),
]

web_django/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.shortcuts import render
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from camnang import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'trangchu/', views.trangchu, name='trangchu'),
    path(r'', include('login.urls')),
    path(r'weather/', include('weather.urls')),
    path(r'hotel/', include('hotel.urls')),
    path(r'camnang/', include('camnang.urls')),
    url(r'search/', views.search_result, name='search'),  
    path('social-auth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/models.py
from django.db import models
from django.db.models.deletion import CASCADE, PROTECT
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Img_slide(models.Model):
    img_id = models.AutoField(primary_key=True, unique=True, null=False)
    img = models.ImageField(max_length=100, default=None, upload_to='slide_hotel_img')
    hotel_id = models.ForeignKey('Hotel', on_delete=models.CASCADE, default='')
     
    def __str__(self):
        return f"{self.img_id}"
    
class Firnish(models.Model):
    firnish_id = models.AutoField(primary_key=True, unique=True, null=False)
    firnish_name = models.CharField(max_length=100, default='') 
    hotel_id = models.ForeignKey('Hotel', on_delete=models.CASCADE, default='')
    
    def __str__(self):
         return self.firnish_name
    
class Room(models.Model):
    room_id = models.AutoField(primary_key=True, unique=True, null=False)
    hotel_id = models.ForeignKey('Hotel', on_delete=models.CASCADE, default='')
    room_name = models.CharField(max_length=100, default='') 
    price = models.FloatField(default=0)
    ROOM_VALUE = (
        ('1', 'Còn phòng'),
        ('0', 'Hết phòng'),
    )
    valu = models.CharField(choices=ROOM_VALUE, default='1', max_length=10)
    imga = models.ImageField(max_length=100, default=None, upload_to='room_img')
    
    def __str__(self):
        return self.room_name
    
class Hotel(models.Model):
    hotel_id = models.AutoField(primary_key=True, unique=True, null=False)
    hotel_name = models.CharField(max_length=200, default='')
    location = models.CharField(max_length=100, default='')
    address = models.CharField(max_length=100, default='')
    star = models.PositiveSmallIntegerField(default='')
    nearby = models.CharField(max_length=100, default='')
    map = models.URLField(max_length=1000, default='')
    phone = models.CharField(max_length=20, default='')
    image = models.ImageField(max_length=100, default=None, upload_to='hotel_img')
    description = models.TextField(default='')
    mprice = models.FloatField(default=0)
    favorite = models.ManyToManyField(User, related_name='favorite', blank=True)
    
    def __str__(self):
        return f"{self.hotel_id}"
    
class Booking(models.Model):
    booking_id = models.AutoField(primary_key=True, unique=True, null=False)
    user = models.CharField(default='', max_length=100)
    hotel_id = models.CharField(default='', max_length=200)
    hname = models.CharField(max_length=500, default='')
    locate = models.CharField(max_length=100, default='')
    room_type = models.CharField(max_length=500, default='')
    room_id = models.CharField(max_length=500, default='')
    book_day = models.DateTimeField(default=timezone.now)
    check_in = models.DateField(default='')
    check_out = models.DateField(default='')
    quanti = models.PositiveSmallIntegerField(default=1)
    name = models.CharField(max_length=100, default='')
    phone = models.CharField(max_length=100, default='')
    cmnd = models.CharField(max_length=100, default='')
    pay = models.CharField(max_length=100, default='')
    total_price = models.CharField(max_length=100, default='')    
    
    def __str__(self):
        return f"{self.user} has booked {self.room_type} from {self.check_in} to {self.check_out}"
    
 
    

    
    
    
    

hotel/forms.py
from django import forms
from .models import Booking
        
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = [
            "booking_id",
            "user",
            "locate",
            "hotel_id",
            "hname", 
            "room_type",
            "room_id",
            "book_day",
            "check_in",
            "check_out",
            "name",
            "phone",
            "cmnd",
            "pay", 
            "total_price",
        ]
        
class BookingRoom(forms.ModelForm):
    class Meta:
        model = Booking
        fields = [
            "room_id",
            "room_type",
            "check_in",
            "check_out",
        ]

hotel/views.py
from django.shortcuts import render, redirect
from hotel.models import Hotel, Room, Firnish, Img_slide
from camnang.models import Camnang2, Comment
from django.core.paginator import EmptyPage, Paginator
from django.db.models.query import Q
from hotel.models import Hotel, Booking
from hotel.forms import BookingForm, BookingRoom
from camnang.forms import CommentForm
from django.contrib.auth.decorators import login_required
from .filter import HotelFilter
from time import gmtime, strftime
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
import datetime
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from login.tokens import generate_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage,send_mail, BadHeaderError
from web_django import settings
# Create your views here.
def search(request):
    search = request.POST.get('search')
    result1 = Camnang2.objects.filter(Q(camnang_name__icontains=search))  
    result2 = Hotel.objects.filter(Q(location__icontains=search) | Q(hotel_name__icontains=search))
    
    context = {
        'result1': result1,
        'result2': result2,
        'searched': search,
    }
    
    return render(request, 'search.html', context)
    
def hotel (request):
    if request.method == 'POST':
        if 'search' in request.POST:
            return search(request)            
    
    ht = Hotel.objects.all().order_by('-star')
    left1 = Camnang2.objects.order_by('-date')[:1]
    left2 = Camnang2.objects.all().order_by('-date')[2:4]
    right1 = Camnang2.objects.all().order_by('-date')[1:2]
    right2 = Camnang2.objects.all().order_by('-date')[4:6]  
        
    myFilter = HotelFilter(request.GET, queryset=Hotel.objects.all())
    if request.GET.get('mprice')=='lt':
        myFilter = HotelFilter(request.GET, queryset=Hotel.objects.all().order_by('-mprice'))
    elif request.GET.get('mprice')=='gt':
        myFilter = HotelFilter(request.GET, queryset=Hotel.objects.all().order_by('mprice'))
    else: 
        myFilter = HotelFilter(request.GET, queryset=Hotel.objects.all())
        
    haha = myFilter.qs
    p = Paginator(haha, 9)
    page_num = request.GET.get('page', 1)
    
    try:
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)
        
    htel = Hotel.objects.get(hotel_id = 12)
    haha = htel.favorite.filter(id=request.user.id).exists()
            
    context = {
        'left1': left1,
        'right1': right1,
        'left2': left2,
        'right2': right2,
        'items': page,
        'filter': myFilter,
        'ht': ht,
        'haha': haha,
    }
    
    return render(request, 'hotel/khach_san.html', context)


@login_required(login_url='login')
def booking (request, hotel_id):
    hotel = Hotel.objects.filter(hotel_id = hotel_id)
    booked = Room.objects.filter(room_id=request.GET.get('room_id'))
    showtime = strftime("%Y-%m-%d %H:%M:%S", gmtime())

    form = BookingForm(request.POST)
    if request.method == 'POST':
        if 'search' in request.POST:
            return search(request)
        else:
            if form.is_valid():
                form.save()
                current_site = get_current_site(request)
                myuser = User.objects.get(username=request.user)
                email_subject = "Xác nhận đặt khách sạn"
                mesage2 = render_to_string(('hotel/booking_email_confirm.html'),{
                    'username':request.user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(myuser.pk)),
                    'token': generate_token.make_token(myuser)

                })
                email = EmailMessage(
                    email_subject,
                    mesage2,
                    settings.EMAIL_HOST_USER,
                    [request.user.email],
                )
                
                email.fail_silently = True
                email.send()        
                return render(request, 'hotel/booking_success.html', {'form': form})
    
    context = {
        'hotel': hotel,
        'booked': booked,
        'form': form,
        'time': showtime,
    }
    return render(request, 'hotel/booking.html', context)

def hotel_detail (request, hotel_id):
    ht = Hotel.objects.filter(hotel_id = hotel_id)
    fn = Firnish.objects.filter(hotel_id = hotel_id)
    r = Room.objects.filter(hotel_id = hotel_id)
    im = Img_slide.objects.filter(hotel_id = hotel_id)
    user = request.user
    comments = Comment.objects.filter(post_id = hotel_id).order_by('-created_on')
    comment_form = CommentForm()
    qs = Hotel.objects.filter(hotel_id = hotel_id)
    
    check_in = request.GET.get('check_in')
    check_out = request.GET.get('check_out')
    today = datetime.datetime.now().strftime ("%m-%d-%Y")
    check = Room.objects.raw('''
                            select r.* from hotel_room r where (r.hotel_id_id=%s and %s >= %s and %s >= %s)
                            except 
                            select r.* from hotel_room r join hotel_booking b on r.room_name = b.room_type
                            where ((b.check_in <= %s and %s <= b.check_out) or (%s >= b.check_in and %s <= b.check_out))''',[hotel_id, check_out, check_in, check_in, today, check_in, check_in, check_out, check_out])
    br = BookingRoom()
    if request.method == 'POST':
        if 'search' in request.POST:   
            return search(request)
            
        if request.user.is_authenticated:
            if 'comment_submit' in request.POST:
                comment_form = CommentForm(data=request.POST)
                if comment_form.is_valid():
                    comment_form.save()
                else:
                    comment_form = CommentForm() 
        else:
            return redirect('login') 
            
    context = {
        'qs': qs,
        'user': user,
        'comments':comments,
        'form': comment_form,
        'ht': ht,
        'fn': fn,
        'r': r,
        'img': im,
        'check': check,
        'check_in': check_in,
        'check_out': check_out,
        'br': br,
    }        
    return render(request, 'hotel/khach_san_single.html', context)

def success_booking (request):
    if request.method == 'POST':
        if 'search' in request.POST:
            return search(request)          
    return render(request, 'hotel/booking_success.html')

def booking_detail (request, booking_id):
    if request.method == 'POST':
        if 'search' in request.POST:
            return search(request)
    detail = Booking.objects.raw('''select r.*, h.*, b.* from (hotel_hotel h join hotel_booking b on h.hotel_id = cast(b.hotel_id as int)) join hotel_room r on cast(b.room_id as int) = r.room_id
                                    where b.booking_id=%s''', [booking_id])          
    return render(request, 'hotel/booking_detail.html', {'detail': detail})

def wishlist(request):
    ht = Hotel.objects.filter(favorite=request.user)
    return render(request, "hotel/user_wish_list.html", {"wishlist": ht})

def favorite(request, hotel_id):
    htel = get_object_or_404(Hotel, hotel_id = hotel_id)
    if htel.favorite.filter(id=request.user.id).exists():
        htel.favorite.remove(request.user)
        love = get_object_or_404(Hotel, hotel_id = hotel_id)
    else:
        htel.favorite.add(request.user)
        love = ''
    return HttpResponseRedirect(request.META["HTTP_REFERER"], {'love': love})

templates/hotel/booking.html
{% extends 'base1.html' %}
{% load static %}
{% block title %}Đặt khách sạn{% endblock %}
{% block css %}
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.css' %}">
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/hotel.css' %}">
  <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
{% endblock %}

{% block content %}
  <div class="slider-area w-100 ">
    <div class="single-slider hero-overly slider-height2 d-flex align-items-center w-100"
      style="background-image: url({% static 'img/decor/hotel.jpg' %}); width: 100%">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="hero__caption">
              <div class="hero-text1">
              </div>
              <div class="stock-text" data-animation="fadeInUp" data-delay=".8s">
                <h2>Đặt khách sạn</h2>
                <h2>Đặt khách sạn</h2>
              </div>
              <div class="hero-text2 mt-110" data-animation="fadeInUp" data-delay=".9s">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section class="appoinment section">
    <div class="container">
      <div class="row">
        <div class="col-lg-4" style="text-align: center">
          <div class="mt-3 p-4" style="background: #fff;">
            <div class="feature-icon mb-3">
              <i class="fas fa-headset" style="color: #e12454; font-size: 50px"></i>
            </div>
            <span class="h3" style="font-weight: bold; font-family: "Exo", sans-serif;">Mọi thắc mắc xin liên hệ!</span>
            {% for ht in hotel %}
            <h2 class="text-color mt-3" style="color: #223a66; font-weight: bold">{{ht.phone}}</h2>
            {% endfor %}
          </div>
          <img src="https://static.mservice.io/img/momo-upload-api-211014142646-637698184063006489.jpg" class="img-fluid">

        </div>

        <div class="col-lg-8" style="font-size: 20px">
          <div class="appoinment-wrap mt-5 mt-lg-0 pl-lg-5">
            <h2 class="mb-2 title-color" style="color: #223a66; font-weight: 800; font-size: 50px; text-align: center">ĐẶT KHÁCH SẠN</h2>
            <p class="mb-4">Đặt phòng khách sạn giá rẻ và thanh toán tiện lợi bằng Paypal. Rất nhiều ưu đã cho bạn. Đi khắp nơi chẳng còn lo chốn nghỉ chân chỉ với vài thao tác.</p>
            
            <form id="booking" class="appoinment-form" method='POST' action=".">
              {% csrf_token %} 
              {% for ht in hotel %}
              <input type="text" name="user" maxlength="100" required id="id_user" value="{{request.user}}" style="display: none">
              <input type="text" name="hotel_id" maxlength="200" required id="id_hotel_id" value="{{ht.hotel_id}}" style="display: none">
              <input type="text" name="room_id" maxlength="500" required id="id_room_id" value="{{request.GET.room_id}}" style="display: none">
              <input type="text" name="book_day" required id="id_book_day" value="{{time}}" style="display: none">

              <div class="col-lg-12">
                <div class="form-group">
                  <label for="id_hname"><b>Tên khách sạn</b></label>
                  <input type="text" name="hname" maxlength="100" required id="id_hname" value="{{ht.hotel_name}}" class="form-control" readonly>
                </div>
              </div>

              <div class="col-lg-12">
                <div class="row">
                  <div class="col-lg-3">
                    <div class="form-group">
                      <label for="id_locate"><b>Khu vực</b></label>
                      <input type="text" name="locate" maxlength="100" required id="id_locate" value="{{ht.location}}" class="form-control" readonly>
                    </div>
                  </div>
                  <div class="col-lg-9">
                    <div class="form-group">
                      <label><b>Địa chỉ</b></label>
                      <input type="text" value="{{ht.address}}" class="form-control" readonly>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}

              <div class="col-lg-12">
                <div class="row">
                  {% for r in booked %}
                  <div class="col-lg-9">
                    <div class="form-group">
                      <label for="id_locate"><b>Tên phòng</b></label>
                      <input type="text" name="room_type" maxlength="500" required id="id_room_type" value="{{r.room_name}}" class="form-control" readonly>
                    </div>
                  </div>
                  {% endfor %}

                  <div class="col-lg-3">
                    <div class="form-group">
                      <label for="id_quanti"><b>Số lượng</b></label>
                      <input type="number" name="quanti" min="0" required id="id_quanti" value='1' class="form-control" readonly>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-lg-12">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label for="id_check_in"><b>Ngày nhận phòng</b></label>
                      <input type="text" name="check_in" required id="id_check_in" value="{{request.GET.check_in}}" class="form-control" readonly>
                    </div>
                  </div>

                  <div class="col-lg-6">
                    <div class="form-group">
                      <label for="id_check_out"><b>Ngày trả phòng</b></label>
                      <input type="text" name="check_out" required id="id_check_out" value="{{request.GET.check_out}}" class="form-control" readonly>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group">
                  <label for="id_name"><b>Họ và tên</b></label>
                  <input type="text" name="name" maxlength="100" required id="id_name" class="form-control" >
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group">
                  <label for="id_phone"><b>Số điện thoại</b></label>
                  <input type="text" name="phone" maxlength="100" required id="id_phone" class="form-control">
                </div>
              </div>

              <div class="col-lg-12">
                <div class="form-group">
                  <label for="id_cmnd"><b>CMND/CCCD</b></label>
                  <input type="text" name="cmnd" maxlength="100" required id="id_cmnd" class="form-control">
                </div>
              </div>

              <div class="col-lg-12" style="margin-bottom: 100px">
                <div class="form-group">
                  <label for="id_pay"><b>Chọn phương thức thanh toán</b></label>
                  <select name="pay" maxlength="100" required id="id_pay" onchange='pmethod()'>
                    <option name="pay" value="Trực tiếp" selected>Trực tiếp</option>
                    <option name="pay" value="Paypal">PayPal</option>
                  </select>
                </div>
              </div>

              <div class="col-lg-12"><hr></div>

              {% for r in booked %}
              <div class="col-lg-12">
                <div class="form-group">
                  <img src="{% static 'img/decor/dollar.png' %}" width="40px" height="40px">
                  <label for="id_total_price" style="color: #e12454"><b>THÀNH TIỀN: </b></label>
                  <span style="font-size: 30px; color: #111; font-weight: bold">$</span>
                  <input type="text" name="total_price" maxlength="100" required id="id_total_price" value="{{r.price}}" style="width: 100px; font-size: 30px; font-weight: bold; background: none; outline: none; border: none" readonly>
                </div>
              </div>
              {% endfor %}

              <div class="col-lg-12"><hr></div>
              
              <div class="col-lg-12" id="pay_method" style="padding-left: 0px !important">
                  <button class="btn" style="width: 100% !important; font-size: 15px" type="submit" id='submit_button'>Đặt phòng<i class=" ml-2 fas fa-chevron-right ml-2"></i></button>
              </div>

              <button class="btn" style="width: 100% !important; font-size: 15px; display: none" type="submit" id='submit_button'>Đặt phòng<i class=" ml-2 fas fa-chevron-right ml-2"></i></button>

              <div id='paypal_method' style="display: none;">
                <div id="paypal-button-container"></div>
                  <script src="https://www.paypal.com/sdk/js?client-id=AaBQ_dMZ9_nyx43GRhA1cw5HJ7xQuioNDx5VAp7MyoTdE704ZuSy5lm03AT0R8k-KO8GfNzISSG7wMqo&currency=USD"></script>
                  <script>
                      paypal.Buttons({
                          createOrder: function(data, actions) {
                              return actions.order.create({
                                  purchase_units: [{
                                      amount: {
                                        value: parseFloat($('input#id_total_price').val())
                                      }
                                  }]
                              });
                          },
              
                          onApprove: function(data, actions) {
                              return actions.order.capture().then(function(orderData) {
                                  console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                                  var transaction = orderData.purchase_units[0].payments.captures[0];
                                  document.getElementById('submit_button').click();
                              });
                          }
                      }).render('#paypal-button-container');
                  </script>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %} 

{% block js %}
  <script>
    function pstar(){
      var price = document.getElementById('id_total_price').value
      var checkin = document.getElementById('id_check_in').value
      var checkout =  document.getElementById('id_check_out').value
      var total_price = 0

      price = parseFloat(price)
      checkin = parseInt(checkin.slice(8))
      checkout = parseInt(checkout.slice(8))

      if (checkin == checkout)
        total_price = price
      else
        total_price = price * (checkout - checkin)    
        
      document.getElementById('id_total_price').value = total_price;
    }

    function pmethod(){
      var show_method = document.getElementById('pay_method')
      var obj = document.getElementById('id_pay')
      var value = obj.value
      var paypal = document.getElementById('paypal_method')

      if (value == 'Trực tiếp') {
        show_method.innerHTML= `<button class="btn btn-main-2 btn-round-full" style="width: 100% !important" type="submit">Đặt phòng<i class=" ml-2 fas fa-chevron-right ml-2"></i></button>`
        paypal.style.display="none"
      }
      else if (value == 'Paypal') {
        paypal.style.display="block"
        show_method.innerHTML=''
      } 
    }

  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.3.2/jquery-migrate.min.js"></>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
  <script src="{% static 'js/hotel.js' %}"></script>
  <script src="{% static 'js/nice-select.js' %}"></script>
{% endblock %}

templates/hotel/booking_detail.html
{% extends 'base1.html' %}
{% load static %}
{% block title %}Chi tiết khách sạn{% endblock %}
{% block css %}
    <style>
      button:hover {
        background: #FF4A52;
      }
    </style>
{% endblock %}

{% block content%}
  <br><br>

  <section class="section doctor-single">
    {% for item in detail %}
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-6">
          <div class="doctor-img-block">
            <img src="/media/{{item.imga}}" alt="" class="img-fluid w-100">
            <div class="info-block mt-4">
              <h4 class="mb-0"><b>Phòng:</b> {{item.room_name}}</h4>
            </div>
          </div>
        </div>
  
        <div class="col-lg-8 col-md-6">
          <div class="doctor-details mt-4 mt-lg-0">
            <h2 class="text-md" style="color: #e12454">{{item.hotel_name}}</h2>
            <p class="starr mb-2">
              <span id="x-star" class="numstar" style="display: none">{{item.star}}</span>
            </p>
            <div class="divider my-4"></div>
            <p><b>Địa chỉ: </b>{{item.address}}</p>
            <p><b>Số điện thoại liên hệ: </b>{{item.phone}}</p>
            <p><b>Ngày đặt: </b>{{item.book_day}}</p>
            <p><b>Ngày nhận phòng: </b>{{item.check_in}}</p>
            <p><b>Ngày trả phòng: </b>{{item.check_out}}</p>
            <p><b>Số lượng: </b>{{item.quanti}}</p>
            <p><b>Phương thức thanh toán: </b>{{item.pay}}</p>
            <h4><b>Thành tiền: </b><span style="color: #FF4A52">${{item.total_price}}</span></h4>
  
            <a href="/hotel/detail/{{item.hotel_id}}" class="btn btn-main-2 btn-round-full mt-3">Đặt lại<i class="icofont-simple-right ml-2"></i></a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </section>
{% endblock %}

{% block js %}
<script>
  function pstar(){
    var objects = document.querySelectorAll('.starr')
    var star=''
    for (i=0; i < objects.length; i++){
      var numstar = parseInt(objects[i].querySelector('.numstar').innerHTML)
      for (j=0; j < numstar; j++){
        star = star + '<span class="star1 fa fa-star text-warning"></span>'
      }
      objects[i].innerHTML = star
      star =''
    }
  }
</script>
{% endblock %}

templates/hotel/booking_email_confirm.html
{% autoescape off %}
NAPUN - Cẩm nang du lịch và Đặt khách sạn
Chào {{username}}

Cảm ơn bạn đã đặt khách sạn tại NAPUN.
Chúc bạn có một chuyến nghĩ dưỡng/công tác an lành.

Kiểm tra tại đây:
https://{{ domain }}:8000{% url 'history' %}
{% endautoescape %}

templates/hotel/booking_success.html
{% extends 'base1.html' %}
{% load static %}
{% block title %}Đặt thành công{% endblock %}
{% block css %}
    <style>
      button:hover {
        background: #FF4A52;
      }
    </style>
{% endblock %}

{% block content%}
  <br><br><br><br><br><br>
  <section>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="confirmation-content text-center">
              <i class="far fa-check-circle text-lg" style="color: #ff5f13; font-size: 50px;"></i>
                <h2 class="mt-3 mb-4" style="font-size: 44px; font-weight: 700; color: #222">Đặt khách sạn thành công !!!</h2>
                <h5 class="mt-3">Khám phá và trải nghiệm cùng NaPun nào</h5>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}