hotel/urls.py
from django.urls import path
from hotel import views

urlpatterns = [
    path(r'', views.hotel, name="hotel"),
    path(r'detail/<int:hotel_id>/', views.hotel_detail, name="hotel_detail"),
    path(r'booking/<int:hotel_id>/', views.booking, name="booking"),
    path(r'booking_success/', views.success_booking, name="booking_success"),
    path(r'booking/detail/<int:booking_id>', views.booking_detail, name="booking_detail"),
    path("favorite/add/<int:hotel_id>", views.favorite, name='favorite'),
    path("favorite/", views.wishlist, name='user_favorite'),
]

web_django/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.shortcuts import render
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from camnang import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'trangchu/', views.trangchu, name='trangchu'),
    path(r'', include('login.urls')),
    path(r'weather/', include('weather.urls')),
    path(r'hotel/', include('hotel.urls')),
    path(r'camnang/', include('camnang.urls')),
    url(r'search/', views.search_result, name='search'),  
    path('social-auth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/forms.py
from django.core.mail import message
from django.forms import ModelForm, fields
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .models import *


class RegistrationForm(forms.Form):
    username = forms.CharField(label=None, max_length=30)
    email = forms.EmailField(label='')
    password1 = forms.CharField(label='', widget=forms.PasswordInput())
    password2 = forms.CharField(label='', widget=forms.PasswordInput())

    def clean_password2 (self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1==password2 and password1:
                return password2
        raise forms.ValidationError("Mat khau khong hop le")
    
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError("ten Tai khoan da ton tai")
    
    def save(self):
        User.objects.create_user(username=self.cleaned_data['username'], email=self.cleaned_data['email'], password=self.cleaned_data['password1'])


# class EditProfile (UserChangeForm):
class EditProfile (forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'last_name',
            'first_name', 
            'email',
        )

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'        
    
    
class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')
  
def should_be_empty(value):
    if value:
        raise forms.ValidationError('Field is not empty')    
    
class contactForm(forms.Form):
    name = forms.CharField(max_length=80)
    message = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField()
    forcefield = forms.CharField(
        required=False, widget=forms.HiddenInput, label="Leave Empty", validators=[should_be_empty]
    )

templates/contact.html
{% extends 'base1.html' %}
{% load static %}
{% block title %}Liên hệ{% endblock %}
{% block css %}
    <style>
        #id_name {
            width: 100%;
        }

        #id_message {
            width: 100%;
        }

        #id_email {
            width: 100%;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="slider-area w-100 ">
        <div class="single-slider hero-overly slider-height2 d-flex align-items-center w-100" style="background-image: url({% static 'img/decor/contact.jpg' %}); width: 100%">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="hero__caption">
                            <div class="hero-text1">
                            </div>
                            <div class="stock-text" data-animation="fadeInUp" data-delay=".8s">
                                <h2>Liên hệ</h2>
                                <h2>Liên hệ</h2>
                            </div>
                            <div class="hero-text2 mt-110" data-animation="fadeInUp" data-delay=".9s">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        
    <div class="container section" id="section-team">
        <div class="row justify-content-center text-center mb-5">
            <div class="ab-us mb-5 d-flex">
            <img src="{% static 'img/decor/left-wing.png' %}" width="90px" height="90px" alt="">
            <h2 class="heading" data-aos="fade-up" style="font-weight: bold; font-size: 60px; color: #ff5f13;">VỀ CHÚNG TÔI</h2>
            <img src="{% static 'img/decor/right-wing.png' %}" width="90px" height="90px" alt="">
            </div>
        </div>
    
        <div class="row">
            <div class="col-md-6 col-lg-6" data-aos="fade-up" data-aos-delay="100">
            <div class="block-2">
                <div class="flipper">
                <div class="front" style="background-image: url({% static 'img/contact/tv1.jpg' %})">
                    <div class="box">
                    <h2>Bích Phượng</h2>
                    <p>Thành viên 1</p>
                    </div>
                </div>
                <div class="back">
                    <!-- back content -->
                    <blockquote>
                    <p>&ldquo;Cuộc sống không phải luôn luôn hoàn hảo nhưng nó là kết quả của những gì bạn tạo ra. Vì thế hãy làm nó có giá trị, làm sao cho nó đáng nhớ và đừng bao giờ để ai đó đánh cắp hạnh phúc của bạn.&rdquo;</p>
                    </blockquote>
                    <div class="author d-flex">
                    <div class="image mr-3 align-self-center">
                        <img src="{% static 'img/contact/tv1.jpg' %}" alt="">
                    </div>
                    <div class="name align-self-center">Bích Phượng<span class="position">Thành viên 1</span></div>
                    </div>
                </div>
                </div>
            </div> <!-- .flip-container -->
            </div>
    
            <div class="col-md-6 col-lg-6" data-aos="fade-up" data-aos-delay="200">
            <div class="block-2">
                <!-- .hover -->
                <div class="flipper">
                <div class="front" style="background-image: url({% static 'img/contact/tv2.jpg' %})">
                    <div class="box">
                    <h2>Thanh Nhàn</h2>
                    <p>Thành viên 2</p>
                    </div>
                </div>
                <div class="back">
                    <!-- back content -->
                    <blockquote>
                    <p>&ldquo;Lo lắng chỉ làm lãng phí thời gian, nó không làm thay đổi gì cả, ngoài việc lấy đi niềm vui và làm cho bạn lúc nào cũng bận rộn mà chẳng hoàn tất được gì cả.&rdquo;</p>
                    </blockquote>
                    <div class="author d-flex">
                    <div class="image mr-3 align-self-center">
                        <img src="{% static 'img/contact/tv2.jpg' %}" alt="">
                    </div>
                    <div class="name align-self-center">Thanh Nhàn<span class="position">Thành viên 2</span>
                    </div>
                    </div>
                </div>
                </div>
            </div> <!-- .flip-container -->
            </div>
        </div>
        </div>
    </div>
       
    <section class="contact-section">
        <div class="container">                    
            <div class="row">
                <br><br>
                <div class="col-12">
                    <h2 class="contact-title">Liên hệ với chúng tôi</h2>
                </div>
                <div class="col-lg-8">
                    <form method="POST" class="form-contact contact_form"  id="contactForm" novalidate="novalidate">
                        {% csrf_token %} 

                        {% for hidden in form.hidden_fields %}
                        {{hidden}}
                        {% endfor %}

                        {% for field in form.visible_fields %}
                        <div class="form-group">
                            {{ field.errors }}


                            <label>{{ field.label_tag }}</label>
                            <p>{{ field }}</p>
                            {% comment %} <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input class="form-control valid" name="message-name" id="name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nhập tên'" placeholder="Nhập tên">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input class="form-control valid" name="message-email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nhập email'" placeholder="Nhập email">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nhập tin nhắn'" placeholder=" Nhập tin nhắn"></textarea>
                                    </div>
                                </div>
                            </div> {% endcomment %}
                        </div>
                        {% endfor %}
                        <div class="form-group mt-3">
                            <button type="submit" class="button button-contactForm boxed-btn">Gửi</button>
                        </div>
                    </form>
                </div>
                <div class="col-lg-3 offset-lg-1">
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="fas fa-home"></i></span>
                        <div class="media-body">
                            <h3>1111 Kha Vạn Cân, Linh Trung, Thủ Đức, TP.HCM</h3>
                        </div>
                    </div>
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="fas fa-phone"></i></span>
                        <div class="media-body">
                            <h3>+(84) 1234-567-8901</h3>
                        </div>
                    </div>
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="fas fa-envelope"></i></span>
                        <div class="media-body">
                            <h3>napun28@gmail.com</h3>
                            <p>Gửi mail bất cứ lúc nào!</p>
                        </div>
                    </div>
                </div>
            </div>  
        </div>            
    </section>
{% endblock %}
       

templates/search.html
{% extends 'base1.html' %}
{% load static %}
{% block title %}NAPUN{% endblock %}
{% block css %}
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.css' %}">
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/hotel.css' %}">
  <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
{% endblock %}

{% block content %}
        <div class="slider_area">
            <div class="slider_active owl-carousel">
                <div class="single_slider  d-flex align-items-center" style="background-image: url({% static 'img/slider/dulich.jpg' %});">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-xl-12 col-md-12"></div>
                        </div>
                    </div>
                </div>
                <div class="single_slider  d-flex align-items-center" style="background-image: url({% static 'img/slider/vungtau.jpg' %});">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-xl-12 col-md-12">
                                <div class="slider_text text-center">
                                    <h3>Vũng Tàu</h3>
                                    <p>Vũng Tàu mang trong mình đầy đủ cảnh sắc của núi trời, non nước</p>
                                    <a href="{% url 'cn_vungtau' %}" class="boxed-btn">Khám phá</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="single_slider  d-flex align-items-center" style="background-image: url({% static 'img/slider/hue.jpg' %});">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-xl-12 col-md-12">
                                <div class="slider_text text-center">
                                    <h3>Huế</h3>
                                    <p style="text-align: center !important;">Thành phố Huế mộng, mơ đậm đà bản sắc dân tộc</p>
                                    <a href="{% url 'cn_hue' %}" class="boxed-btn">Khám phá</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="single_slider  d-flex align-items-center" style="background-image: url({% static 'img/slider/sapa.jpg' %});">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-xl-12 col-md-12">
                                <div class="slider_text text-center">
                                    <h3>Lào Cai</h3>
                                    <p style="text-align: center !important;">Đồi núi cao với những thửa ruộng bậc thang tuyệt đẹp</p>
                                    <a href="{% url 'cn_laocai' %}" class="boxed-btn">Khám phá</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="single_slider  d-flex align-items-center" style="background-image: url({% static 'img/slider/hanoi.png' %});">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-xl-12 col-md-12">
                                <div class="slider_text text-center">
                                    <h3>Hà Nội</h3>
                                    <p style="text-align: center !important;">Hà Nội, thủ đô của Việt Nam, nổi tiếng với kiến trúc trăm tuổi và nền văn hóa phong phú</p>
                                    <a href="{% url 'cn_hanoi' %}" class="boxed-btn">Khám phá</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container" style="max-width: 1080px;">
            <div class="notif">
                <div class="notif_list">
                    <span class="text-uppercase notif_title">
                        <b>NAPUN: </b>
                    </span>
                    <span class="notif_content slide100-txt" data-in="fadeInDown" data-out="fadeOutDown">
                        <span class="notif_conntent_items slide100-txt-item animated visible-false" style="color: #666699;">
                            Người Việt Nam đi khắp Việt Nam
                        </span>

                        <span class="notif_conntent_items slide100-txt-item animated visible-false" style="color: #666699;">
                            Khách sạn muôn nơi, thả ga lựa chọn
                        </span>

                        <span class="notif_conntent_items slide100-txt-item animated visible-false" style="color: #666699;">
                            Thỏa sức khám phá chẳng ngại âu lo
                        </span>
                    </span>
                </div>
            </div>
        </div>

        <div class="container-fluid py-3">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="mb-3 pb-3">
                            <a href="{% url 'hotel' %}"><img class="img-fluid w-100" src="{% static 'img/decor/dulich.jpg' %}" alt=""></a>
                        </div>
                        <div class="d-flex align-items-center justify-content-between py-2 px-4 mb-3">
                            <img src="{% static 'img/decor/search.png' %}" alt="" width="40px" height="40px">
                            <h3 class="m-0 h3" style=" color: #ff5f13">Kết quả tìm kiếm cho <span style="font-style: italic;">" {{ searched }} "</span></h3>
                        </div>
                        <div class="row mb-3">
                            <div class="col-lg-12">
                                <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
                                    <h3 class="m-0 h3">Cẩm nang du lịch</h3>
                                    <a class="text-secondary font-weight-medium text-decoration-none" href="{% url 'cn_detail' %}">Xem tất cả</a>
                                </div>
                            </div>  
                        </div>
                        <div class="row mb-3">
                            {% if result1 %}
                                {% for l in result1 %}
                                    <div class="col-lg-4">
                                        <div class="position-relative mb-3 haha">
                                            <a href="{{l.link}}"><img class="img-fluid w-100" src="/media/{{l.bg}}" style="object-fit: cover;"></a>
                                            <div class="overlay position-relative bg-light">
                                                <div class="mb-2" style="font-size: 14px;">
                                                    <span>{{l.date}}</span>
                                                </div>
                                                <a class="h4" href="{{l.link}}">{{l.camnang_name}}</a>
                                                <p class="m-0">{{l.description}}</p>
                                                <div class="mb-2" style="font-size: 14px;">
                                                    <span>
                                                        <i class="far fa-eye"></i>
                                                        <span id="view">{{l.view}}</span> 
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <div class="col-lg-12">
                                    <center><h6 style="font-family: Poppins, Arial, sans-serif !important; color: #999">Không tìm thấy kết quả phù hợp :)))</h6></center>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="mb-3 pb-3">
                            <div class="row mb-3">
                                <div class="col-12">
                                    <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
                                        <h3 class="m-0 h3">Khách sạn</h3>
                                        <a class="text-secondary font-weight-medium text-decoration-none" href="{% url 'hotel' %}">Xem tất cả</a>
                                    </div>
                                </div>
                            </div> 

                            <section class="ftco-section" style="background: none">
                              <div class="container">
                                <div class="row">
                                    {% if result2 %}
                                        {% for item in result2 %}
                                        <div class="col-md-4">
                                            <div class="project-wrap hotel">
                                              <a href="/hotel/detail/{{item.hotel_id}}" class="img hotel-img"
                                                style="background-image: url(/media/{{item.image}});">
                                                <span class="price">{{item.mprice}} VND/ngày</span>
                                              </a>
                                              <div class="text p-4">
                                                <p class="star mb-2">
                                                    <span class="star1 fa fa-star text-warning"></span>
                                                </p>
                                                <span class="area">{{item.location}}</span>
                                                <h3><a href="/hotel/detail/{{item.hotel_id}}" id="hotel-name">{{item.hotel_name}}</a></h3>
                                                <p class="location"><span class="fa fa-map-marker"></span> {{item.address}}</p>
                                                <ul>
                                                  <li>
                                                    <span class="flaticon flaticon-route"></span>
                                                    <span id="nearby">Gần {{item.nearby}}</span>
                                                  </li>
                                                </ul>
                                              </div>
                                            </div>
                                          </div>
                                        {% endfor %}
                                    {% else %}
                                        <div class="col-lg-12">
                                            <center><h6>Không tìm thấy kết quả phù hợp :)))</h6></center>
                                        </div>
                                    {% endif %}
                                </div>
                              </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid py-3">
            <div class="container">
                <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
                    <h3 class="m-0 h3 orange">Khám phá Việt Nam</h3>
                </div>
                <div class="position-relative">
                    <iframe width="100%" height="600px" src="https://www.youtube.com/embed/Au6LqK1UH8g" allowfullscreen></iframe>
                </div>
            </div>
        </div>
{% endblock %}

{% block js %}
    <script>
        function pstar(){
            var objects = document.querySelectorAll('.starr')
            var star=''
            for (i=0; i < objects.length; i++){
            var numstar = parseInt(objects[i].querySelector('.numstar').innerHTML)
            for (j=0; j < numstar; j++){
                star = star + '<span class="star1 fa fa-star text-warning"></span>'
            }
            objects[i].innerHTML = star
            star =''
            }
        }
    </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.3.2/jquery-migrate.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
  <script src="{% static 'js/hotel.js' %}"></script>
  <script src="{% static 'js/nice-select.js' %}"></script>
{% endblock %}
    